import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  return (
    <html lang="pt-BR">
      <body
        className={`min-h-screen flex flex-col sm:px-20 px-7 py-16 ${quicksand.variable} ${quicksand.className} antialiased`}
      >
        <div className="flex flex-col items-center justify-between h-full grow">
          {children}
        </div>
      </body>
    </html>
  );
}
